site:
  title: My API Document
  start_page: docs::index.adoc

content:
  sources:
    - url: .
      branches: main
      start_path: docs  # Adjust this based on your folder structure

ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true

runtime:
  fetch: true


output:
  dir: ./public


