site:
  title: My API Document
  start_page: docs::index.adoc



content:
  sources:
    - url: .
      branches: main

ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true

output:
  dir: ./public
